services:
  matrix-wordle:
    build: .
    container_name: matrix-wordle
    volumes:
      - ./data:/data
    environment:
      LANGUAGE: "en" # or "fr"
      HOMESERVER: "https://matrix.org"
      STATE_DIR: "/data"
      USERNAME: "wordle-bot"
      PASSWORD: "password" # or ACCESS_TOKEN=syt_...
